redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jhach\\Desktop\\Projects\\LingoBeats-Repository\\client\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\jhach\\Desktop\\Projects\\LingoBeats-Repository\\client"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "http://3.94.62.63:3000/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]